### ISSUE TITLE
Deprecated imports need to be changed. 

### ISSUE THREAD

**Issue by GoofyCoderGuy** [FRC9015/Crescendo#1]
import com.revrobotics.CANSparkMaxLowLevel.MotorType;

CANSparkMaxLowLevel is deprecated and needs to be changed.

import edu.wpi.first.wpilibj2.command.CommandBase;

CommandBase is deprecated and needs to be changed.

**Comment by REVSIX** [comment]
Resolved Issues by changing what import it called
