### ISSUE TITLE
Add more paths and more PathPlanner functionality

### ISSUE THREAD

**Issue by Omkaarcodes** [FRC9015/Crescendo#28]
This issue is for adding more path planner paths and functionality to the codebase, which includes:

- Porting over our autos into the code
- Implementing the auto routines in code
- Potential auto path generation from given position and using limelight data to determine the end position

I will be creating a new branch from this issue, so please add any files, code, etc. to that branch.

Thanks.

**Comment by moyales** [comment]
Hey Omkaar, this is a great idea for an issue to work with, but I also think that this is a bit broad in its scope. I believe each of the tasks listed in your bullet points can be broken down into their own issues. Each issue should correspond to one task and one branch, with the emphasis of each branch having **small** changes. While it may seem annoying to have one issue for every auto routine or every path, it is the best way to ensure we don't run into merge conflicts every time we open a PR.

**Comment by ErinEnriquez** [comment]
I can port them over when I get home later today at 5 or 8.

**Comment by REVSIX** [comment]
I'm going to close this issue and create a new, updated one since we are using yagsl.
