### ISSUE TITLE
Fix Translational Skew in Robot Movement

### ISSUE THREAD

**Issue by REVSIX** [FRC9015/Crescendo#37]
Currently, when moving the robot left and right, you'll notice that it doesn't stay in a straight line. Rather, it begins to move a little forward or backward. The solution will involve some sort of [discretization](https://www.chiefdelphi.com/t/whitepaper-swerve-drive-skew-and-second-order-kinematics/416964), which currently exists, but doesn't seem to be doing anything.

**Comment by GoofyCoderGuy** [comment]
fix your dumb discitize now

**Comment by REVSIX** [comment]
Heading PID Fixes are pushed, pending testing

**Comment by REVSIX** [comment]
Custom Heading PID Did Not work. Next Step is trying YAGSL's commands for it
