### ISSUE TITLE
Swerve module state being set in SwerveSubsytem module.

### ISSUE THREAD

**Issue by lazychino** [FRC9015/Crescendo#39]
Currently [SwerveModule.teleop()](https://github.com/FRC9015/Crescendo/blob/main/src/main/java/frc/robot/subsystems/Swerve/SwerveModule.java#L90) it reads target state and set the motors voltages and is being run in the [SwerveSubsystem.periodic](https://github.com/FRC9015/Crescendo/blob/main/src/main/java/frc/robot/subsystems/Swerve/SwerveSubsystem.java#L212).
This can cause issues since the periodic always run if the bot is enabled and are not meant to have code that changes the robot state.

The code in SwerveModule.teleop should be in [SwerveModule.setState](https://github.com/FRC9015/Crescendo/blob/main/src/main/java/frc/robot/subsystems/Swerve/SwerveModule.java#L73)

updated: bad grammar 😓

**Comment by REVSIX** [comment]
Fixed with YAGSL
