### ISSUE TITLE
SCREW INPUTMANAGER UPDATES. REFACTOR SO IT IS ADAPTABLE.

### ISSUE THREAD

**Issue by GoofyCoderGuy** [FRC9015/Crescendo#40]
Thomas gave some suggestions on how to refactor the InputManager to have it output each type of button so that you can combine them as well as create custom buttons with Booleans. This is better than my approach where I would create a new function for each new feature which isn't ideal.

This will probably look completely different by the time I am done with this.

**Comment by waffleattack** [comment]
To give a better idea of what I meant, you could simply refactor input manager to have a function that takes in an enum and returns the button associated with it. Then the end user can handle any composition on their end

**Comment by GoofyCoderGuy** [comment]
What he said
